### ISSUE TITLE
AircraftSimulator use of bloods?

### ISSUE THREAD

**Issue by ardian-selmonaj** [liuqh16/CloseAirCombat#21]
The class `AircraftSimulator(BaseSimulator)` has an attribute `bloods`. What exactly is the use of it? It will never get updated, except in `SingleCombatTask()`, where the attribute `use_artillery` is anyway always `False` or I did not find it as a config parameter, respectively. 

Thanks for your help!

**Comment by Jackory** [comment]
yeah，the blood and artillery reward has been deprecated.



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 14, 2023 00:40 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [liuqh16/CloseAirCombat] AircraftSimulator use of bloods? (Issue #21)




 
The class AircraftSimulator(BaseSimulator) has an attribute bloods. What exactly is the use of it? It will never get updated, except in SingleCombatTask(), where the attribute use_artillery is anyway always False or I did not find it as a config parameter, respectively.
 
Thanks for your help!
