### ISSUE TITLE
训练速度能提升么

### ISSUE THREAD

**Issue by happy820** [liuqh16/CloseAirCombat#3]
您好，用了您这个环境，感觉非常好，很适合做多机空战的训练，真心感激您的分享。
这边有个问题，就是我想使用您的环境进行8v8战机的对抗训练，训练速度慢，6小时训练了几十万步，我看到gpu使用是2000m不到，想请问下您是否有什么办法能够提升这个训练速度，谢谢。

**Comment by happy820** [comment]
我开了多进程训练，gpu占用没有变化，训练速度没变感觉。

**Comment by Jackory** [comment]
在你的配置下，1v1自搏训练，训练速度如何？

**Comment by happy820** [comment]
1亿步，3天左右&nbsp;


空空
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuhua ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 晚上8:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuqh16/CloseAirCombat] 训练速度能提升么 (Issue #3)





 
在你的配置下，1v1自搏训练，训练速度如何？

**Comment by Jackory** [comment]
那说明就是 8v8 和 1v1速度差别不大，用128核cpu和2080Ti 显卡，1v1半天就训好了，建议提高配置

**Comment by happy820** [comment]
你也是跑1亿步么，1v1，有那么快么。。
&nbsp;


空空
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuhua ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 下午3:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuqh16/CloseAirCombat] 训练速度能提升么 (Issue #3)





 
那说明就是 8v8 和 1v1速度差别不大，用128核cpu和2080Ti 显卡，1v1半天就训好了，建议提高配置

**Comment by Jackory** [comment]
是的，注意我一般开32个并行环境采样

**Comment by Jackory** [comment]
注意我说的是naive-selfplay，不是加载预训练模型的hierarchy self-play，hierarchy确实需要三天才能达到1e8 step

**Comment by happy820** [comment]
echo "env is ${env}, scenario is ${scenario}, algo is ${algo}, exp is ${exp}, seed is ${seed}"
CUDA_VISIBLE_DEVICES=1 python train/train_jsbsim.py \
&nbsp; &nbsp; --env-name ${env} --algorithm-name ${algo} --scenario-name ${scenario} --experiment-name ${exp} \
&nbsp; &nbsp; --seed ${seed} --n-training-threads 1 --n-rollout-threads 4 --cuda --log-interval 20 --save-interval 20 \
&nbsp; &nbsp; --use-selfplay --selfplay-algorithm "fsp" --n-choose-opponents 4 \
&nbsp; &nbsp; --use-eval --n-eval-rollout-threads 1 --eval-interval 10 --eval-episodes 4 \
&nbsp; &nbsp; --num-mini-batch 5 --buffer-size 2000 --num-env-steps 2e6 \
&nbsp; &nbsp; --lr 3e-4 --gamma 0.99 --ppo-epoch 4 --clip-params 0.2 --max-grad-norm 2 --entropy-coef 1e-3 \
&nbsp; &nbsp; --hidden-size "128 128" --act-hidden-size "128 128" --recurrent-hidden-size 128 --recurrent-hidden-layers 1 --data-chunk-length 8 \
&nbsp; &nbsp; --user-name "happyyyyy" --use-wandb --wandb-name "happyyyyy" \
&nbsp; &nbsp; --use-prior&nbsp; &nbsp;我先在的参数是这样，1v1，这里的--n-choose-opponents 4&nbsp;是不是越大训练效果越好，只要比--n-eval-rollout-threads小就可以。&nbsp;
&nbsp;


空空
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuhua ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 下午3:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuqh16/CloseAirCombat] 训练速度能提升么 (Issue #3)





 
是的，注意我一般开32个并行环境采样

**Comment by happy820** [comment]
哦哦，是这样，我现在是把步长改了。


8v8的速度明显快了一些。&nbsp;


空空
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuhua ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuqh16/CloseAirCombat] 训练速度能提升么 (Issue #3)





 
注意我说的是naive-selfplay，不是加载预训练模型的hierarchy self-play，hierarchy确实需要三天才能达到1e8 step

**Comment by happy820** [comment]
谢谢您的回复，分享的这个项目很好。




空空
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuqh16/CloseAirCombat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月15日(星期六) 下午3:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuqh16/CloseAirCombat] 训练速度能提升么 (Issue #3)





 
注意我说的是naive-selfplay，不是加载预训练模型的hierarchy self-play，hierarchy确实需要三天才能达到1e8 step

**Comment by Jackory** [comment]
1. 你需要调大n_rollout_threads，这是训练时开的并行环境个数，我一般取32；
2. 并不是 n_choose_opponents 越大越好，n_choose_opponents是并行环境中对手的种类个数，如果等于1，并行环境中对手都一样，如果等于2，那么16个环境中的对手是player A，另外16个环境中的对手是player B。

**Comment by happy820** [comment]
好的，谢谢，我改改，建议项目里这几个参数加个注释，这样大家都能快速用起来，小小的建议。
&nbsp;


空空
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuhua ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 下午4:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuqh16/CloseAirCombat] 训练速度能提升么 (Issue #3)





  
你需要调大n_rollout_threads，这是训练时开的并行环境个数，我一般取32；
 
并不是 n_choose_opponents 越大越好，n_choose_opponents是并行环境中对手的种类个数，如果等于1，并行环境中对手都一样，如果等于2，那么16个环境中的对手是player A，另外16个环境中的对手是player B。
