### ISSUE TITLE
1v1/NoWeapon/Selfplay训练了1e8次step后好像没有效果

### ISSUE THREAD

**Issue by brucecui1998** [liuqh16/CloseAirCombat#4]

**Comment by brucecui1998** [comment]
我的训练参数如下
`python train_jsbsim.py    --env-name SingleCombat --algorithm-name ppo --scenario-name 1v1/NoWeapon/Selfplay --experiment-name v1   --seed 1 --n-training-threads 64 --n-rollout-threads 32  --log-interval 1 --save-interval 1   --cuda --use-selfplay --selfplay-algorithm "fsp" --n-choose-opponents 1    --eval-interval 1 --eval-episodes 1   --num-mini-batch 5 --buffer-size 3000 --num-env-steps 1e9  --lr 3e-4 --gamma 0.99 --ppo-epoch 4 --clip-params 0.2 --max-grad-norm 2 --entropy-coef 1e-3   --hidden-size "128 128" --act-hidden-size "128 128" --recurrent-hidden-size 128 --recurrent-hidden-layers 1 --data-chunk-length 8  `
在我分别训练了1e8次step和2e8次steps再渲染后，好像并没有得到预期的效果，再tacview中只有30秒的时间，渲染结果output如下：
`(jsbsim) PS C:\Code\crp\CloseAirCombat\scripts\render> python render_jsbsim.py --model-dir C:\Code\crp\CloseAirCombat\scripts\results\SingleCombat\1v1\NoWeapon\Selfplay\ppo\v1\run2 --env-name SingleCombat --scenario-name 1v1/NoWeapon/Selfplay
choose to use cpu...
AircraftSimulator:A0100 is created!


     JSBSim Flight Dynamics Model v1.1.6 [GitHub build 320/commit b477f6312bee2fd3af4c4e5ba1a3e732ed2b99d4] Apr 30 2021 12:00:59
            [JSBSim-ML v2.0]

JSBSim startup beginning ...

AircraftSimulator:B0100 is created!

Start render ...
A0100 altitude is too low. Total Steps=177
B0100 altitude is too low. Total Steps=177
render episode reward of agent: [[[-219.65625251]
  [-219.39669796]]]
AircraftSimulator:A0100 is deleted!
AircraftSimulator:B0100 is deleted!`
请问是模型的问题嘛，还是我训练时间不够，我看着1e8次的训练，奖励曲线也已经收敛到70多分啦，再接着训练奖励曲线也没有变化了

**Comment by Jackory** [comment]
1e8个step足够了, n_training_thread 置为1，训练再试试

**Comment by brucecui1998** [comment]
你好，n_training_thread 置为1训练后，今天渲染仍然是这个问题

**Comment by Join1ng** [comment]
> 

请问您环境安装成功了吗？想请教一下最后一步- Initialize submodules(*JSBSim-Team/jsbsim*): `git submodule init; git submodule update`是怎么进行的呢

**Comment by Jackory** [comment]
重新验证了一下，根据intro介绍的流程，1v1/NoWeapon/Selfplay能训练出效果。
