### ISSUE TITLE
关于环境配置

### ISSUE THREAD

**Issue by Join1ng** [liuqh16/CloseAirCombat#7]
请问最后一步- Initialize submodules(*JSBSim-Team/jsbsim*): `git submodule init; git submodule update`
具体怎么进行呢？我的理解是已经通过pip安装jsbsim了应该不必再从GitHub上重新下载JSBSim-Team/jsbsim了，那这步主要在什么地方执行呢，非常感谢！

**Comment by Jackory** [comment]
直接终端运行
git submodule init; git submodule update

**Comment by Jackory** [comment]
是的，需要先安装git，建议先对git进行一个初步了解

**Comment by Join1ng** [comment]
> 非常感谢您的回复！我已经安装了git，但不太理解的是这部操作目的是什么，在git cmd中运行了这两句init和upadte，但不知道要怎么跟jsbsim建立联系，请问是要在git cmd中切入之前创建的env环境中的jsbsim目录下再去git submodule init吗

**Comment by Jackory** [comment]
.gitsubmodule 文件给出了配置；在项目根目录运行即可

**Comment by Join1ng** [comment]
谢谢大佬，最终用笨方法把下载的jsbsim文件一股脑放入了项目的jsbsim中的data空文件夹里，终于跑通了，THU的大神真的好强，非常感谢您对我这个初学者的耐心解答
