### ISSUE TITLE
环境配置完成，运行python envs/JSBSim/test/test_baseline_use_env.py出现问题

### ISSUE THREAD

**Issue by jhr25864** [liuqh16/CloseAirCombat#9]
您好，控制台运行python envs/JSBSim/test/test_baseline_use_env.py代码后。会出现下列数据：
 JSBSim Flight Dynamics Model v1.1.6 [GitHub build 320/commit b477f6312bee2fd3af4c4e5ba1a3e732ed2b99d4] Apr 30 2021 12:00:59
            [JSBSim-ML v2.0]

JSBSim startup beginning ...

{'current_step': 1000}
然后程序就终止运行了，没有其他错误信息，请问是什么愿意呢？
环境包有部分与您要求的不一样（shapely没有1.7.1-cp38版本，我下载了1.8.2-cp38版本，gym==0.20.0下载安装失败，控制台报错error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1，所以我下载了gym=0.26.2版本）
盼望您的回复，感激不尽

**Comment by jhr25864** [comment]
后续更新，安装了gym==0.2.0，但是执行代码后，会报错：AttributeError: 'SingleCombatEnv' object has no attribute '_jsbsims'。按照网上类似问题解答，删除pyc文件重新运行，仍然具有这个问题

**Comment by jhr25864** [comment]
后续更新，环境已经一模一样了，但是执行python envs/JSBSim/test/test_baseline_use_env.py仍然会报错AttributeError: 'SingleCombatEnv' object has no attribute '_jsbsims'，请问是什么问题呢？非常感谢

**Comment by JerryWang0202** [comment]
您好，我运行代码后遇到跟您相同的情况，想请问您是如何解决的，期待您的回复，感激不尽

**Comment by EskildMK** [comment]
您好，我最近解决了这个问题。
需要严格按照说明中的版本安装各个包，必要情况下需要对pip进行降级以避免报错（参考https://zhuanlan.zhihu.com/p/581112365），同时torch记得安装GPU版本的就没有问题了。

**Comment by EskildMK** [comment]
您好，我最近解决了这个问题。
需要严格按照说明中的版本安装各个包，必要情况下需要对pip进行降级以避免报错（参考https://zhuanlan.zhihu.com/p/581112365），同时torch记得安装GPU版本的就没有问题了。

**Comment by EskildMK** [comment]
您好，我最近解决了这个问题。
需要严格按照说明中的版本安装各个包，必要情况下需要对pip进行降级以避免报错，同时torch记得安装GPU版本的就没有问题了。
找到正确版本的shapely可以去pypi解决，解决上面的报错可以参考https://zhuanlan.zhihu.com/p/581112365
